%% EEG-BIDS GENERATION SCRIPT

% This script enables the generation of BIDS formatted EEG metadata based
% on the BIDS EEGLAB Toolbox:
% https://github.com/sccn/bids-matlab-tools

% See this youtube video from Arnaud Delorme for additional information:
% https://www.youtube.com/watch?v=xdcRe3ak_IQ&feature=youtu.be 
% Example script: https://github.com/sccn/bids-matlab-tools/blob/master/bids_export_example2.m

% /!\ See the GitHub README page for detailed explanations. /!\
% https://github.com/CorentinWicht/autoBIDS
%% Authors

% Corentin Wicht(script, protocol)
% Michael Mouthon (script, protocol)
% Lucas Spierer (protocol)

% If you have questions or want to contribute to this pipeline, feel free 
% to contact :
% corentin.wicht@unifr.ch, corentinw.lcns@gmail.com
% michael.mouthon@unifr.ch 

% Laboratory for Neurorehabilitation Science
% Neurology Unit, Medicine Section
% Faculty of Science and Medicine,
% University of Fribourg
% Ch. du Musée 5, CH-1700 Fribourg
% https://www3.unifr.ch/med/spierer/en/

% Version 0.1, April 2021
%% Clear workspace, etc
clear variables;close all;clc
%% Parameters prompts

% Paths
addpath([pwd '\Functions'])
addpath([pwd '\Functions\eeglab2021.0'])

% Path of your upper folder containing your data and list all bdf files
Extension='.bdf'; % Raw file as input
FilesFolder = uigetdir('title',...
    'Choose the path of your most upper folder containing your RAW EEG files (in .bdf)');
FileList = dir([FilesFolder '\**/*' Extension]);
[~,NatSortIdx] = natsort({FileList.name});
FileList = FileList(NatSortIdx); % Natural order

% Path of the folder to save filtered and epoched .set
mrk_folder = uigetdir('title',...
    ['OPTIONAL: Choose the path of your most upper folder containing your .mrk files' ...
    ' (if no file, press CANCEL)']);
MRKList = dir([mrk_folder '\**/*.mrk']);
[~,NatSortIdx] = natsort({MRKList.name});
MRKList = MRKList(NatSortIdx); % Natural order

% Specify the path of the electrodes localisation file
[chanloc_file,chanloc_path] = uigetfile('*.*', 'Select the electrodes localisation file for your data (.loc or .xyz)');
chanloc_path=[chanloc_path,chanloc_file]; 

% EEG parameters
EEGParamInstruct = {'How many channels do you work with ?',...
    'What is the reference electrode number (i.e. Cz is 48) ?',...
    'What name would you like to give to the EEGLAB STUDY ?',...
    'Presentation triggers delay (in ms)'};
PromptValues = {'64','48','Study','0'};
PromptInputs = inputdlg(EEGParamInstruct,'Preprocessing parameters',1,PromptValues);
nbchan = str2double(PromptInputs{1});
ref_chan = str2double(PromptInputs{2});
StudyName = PromptInputs{3};
Error_ms = str2double(PromptInputs{4});

% BIDS design parameters
BIDSParamInstruct = {'What is the matching pattern for SUBJECTS (e.g. P* if P1, P2, ...)? ',...
    'Is the matching pattern found in files [1], folders [2] or there is none [0] ?',...
    ['Write the name of the COGNITIVE TASKS',...
    newline '! If more than one task, separate their names by a semi-colon ";" !'],...
    'Is the matching pattern found in files [1] or folders [2] ?',...    
    'If the blocks for one task were recorded in SEPARATE FILES/RUNS, indicate the matchin pattern (e.g. B* for B1, B2,...):',...
    'Is the matching pattern found in files [1], folders [2] or there is none [0] ?',...
    'If the files were recorded in more than 1 SESSION (i.e. the EEG cap was removed in between), indicate again the matchin pattern: (e.g. S* for S1, S2,...)',...
    'Is the matching pattern found in files [1], folders [2] or there is none [0] ?',...
    ['To provide information on participants, use either autogenerated excel files [1] or the EEGLAB popup window [2] ?',...
    newline 'Comment: [1] is faster and as accurate.']};
PromptValues = {'P*','1','GNG;RVIP','1','','0','S*','1','1'};
PromptInputs = inputdlg(BIDSParamInstruct,'BIDS design parameters',1,PromptValues);
Subj = PromptInputs{1}; 
SubjPattern = str2double(PromptInputs{2});
Task = strsplit(PromptInputs{3},';'); 
TaskPattern = str2double(PromptInputs{4}); 
Run = PromptInputs{5}; 
RunPattern = str2double(PromptInputs{6}); 
Session = PromptInputs{7}; 
SessionPattern = str2double(PromptInputs{8}); 
MetaData = PromptInputs{9}; 

% Retrieving list of Subjects
StrPattern = ['(?<=' strrep(Subj,'*','') ')[0-9]*'];
if SubjPattern == 1 % subject string pattern in files
    SubjList = cellfun(@(x) str2double(regexp(x, StrPattern, 'match')),{FileList.name}');
elseif SubjPattern == 2 % subject string pattern in folders
    SubjList = cellfun(@(x) str2double(regexp(x, StrPattern, 'match')),{FileList.folder}');
end

%% GENERATING EXCEL TEMPLATE PARTICIPANT FILE

if str2double(MetaData) == 1
    if ~isfile('ParticipantInfo_BIDS.xlsx') % only if file doesn't exist yet
        
        % Column names
        ColNames = {'EEGFiles','Participant'};
        
        % 1. Data sheet
        if SubjPattern == 1 
            PartTab = [{FileList.name}' num2cell(SubjList)];
        elseif SubjPattern == 2
            TEMP = [{FileList.folder}' repmat({'\'},length(FileList),1) {FileList.name}'];
            Dat = cell(size(TEMP,1),1);
            for k=1:size(TEMP,1); Dat{k,:} = horzcat(TEMP{k,:});
            end
            PartTab = [Dat num2cell(SubjList)];
        end
        
        % Content is adjusted based on responses to BIDS prompt
        % 1.1 Task
        if length(Task)>1; TEMP = cell(size(PartTab,1),1);
            ColNames = [ColNames {'Task'}];
            for k=1:size(PartTab,1)
                TEMP{k} = Task{cellfun(@(x) contains(PartTab{k,1},x),Task)};
            end
            PartTab = [PartTab TEMP];
        else
            ColNames = [ColNames {'Task'}];
            PartTab = [PartTab repmat(Task,size(PartTab,1),1)];
        end
        
        % 1.2 Run
        StrPattern = ['(?<=' strrep(Run,'*','') ')[0-9]*'];
        if RunPattern == 1; TEMP = cell(size(PartTab,1),1);
            ColNames = [ColNames {'Run'}];
            for k=1:size(PartTab,1)
                TEMP{k} = str2double(regexp(PartTab{k,1}, StrPattern, 'match'));
            end; PartTab = [PartTab TEMP];
        elseif RunPattern == 2; TEMP = cell(size(PartTab,1),1);
            ColNames = [ColNames {'Run'}];
            for k=1:size(PartTab,1)
                TEMP{k} = str2double(regexp(PartTab{k,1}, StrPattern, 'match'));
            end; PartTab = [PartTab TEMP];
        end
        
        % 1.3 Session
        StrPattern = ['(?<=' strrep(Session,'*','') ')[0-9]*'];
        if SessionPattern == 1; TEMP = cell(size(PartTab,1),1);
            ColNames = [ColNames {'Session'}];
            for k=1:size(PartTab,1)
                TEMP{k} = str2double(regexp(PartTab{k,1}, StrPattern, 'match'));
            end; PartTab = [PartTab TEMP];
        elseif SessionPattern == 2; TEMP = cell(size(PartTab,1),1);
            ColNames = [ColNames {'Session'}];
            for k=1:size(PartTab,1)
                TEMP{k} = str2double(regexp(PartTab{k,1}, StrPattern, 'match'));
            end; PartTab = [PartTab TEMP];
        end
        
        % Write the excel file
        PartTab = [PartTab  cell(length(FileList),2)];
        ColNames = [ColNames {'HeadCircumference','SubjectArtefactDescription'}]; 
        PartTab = cell2table(PartTab,'VariableNames',ColNames);
        writetable(PartTab,'ParticipantInfo_BIDS.xlsx','Sheet','DATA')

        % 2. Description sheet
        ColNames = PartTab.Properties.VariableNames';
        PartDesc = [ColNames cell(length(ColNames),2)];
        PartDesc = cell2table(PartDesc,'VariableNames',{'Vars','Description','Levels'});
        writetable(PartDesc,'ParticipantInfo_BIDS.xlsx','Sheet','DESC')

        % Open interface with excel     
        % Link to Excel
        Excel = actxserver('Excel.Application');
        Excel.Workbooks.Open([pwd '\ParticipantInfo_BIDS.xlsx']);

        % Open the Excel spreadsheet
        Excel.Visible = 1; 

        % Wait Bar 
        Fig=msgbox(['Please fill the excel sheet with Participants metadata.',...
            newline 'The sheet was autofilled with most important information, please do not delete!'... 
            newline newline 'THE CODE WILL CONTINUE ONCE YOU PRESS OK'],'WAIT','warn'); 
        uiwait(Fig);
        close all
        Excel.ActiveWorkbook.Save; 
        Excel.Quit; % Close the activex server
    end

    % Load data
    PartInfoData = readtable('ParticipantInfo_BIDS.xlsx','Sheet','DATA');
    PartInfoColNames = PartInfoData.Properties.VariableNames;
    PartInfoData = table2cell(PartInfoData);
    PartInfoDesc = readtable('ParticipantInfo_BIDS.xlsx','Sheet','DESC');
    PartInfoDesc = table2cell(PartInfoDesc);
end

%% LOADING DATA & BUILDING STUDY 

% Prompt to load existing STUDY
LoadSTUDY = questdlg('Would you like to load an existing EEGLAB STUDY ?', ...
	'LOAD EEGLAB STUDY', 'YES','NO','NO');

if strcmp(LoadSTUDY,'NO')
    % Create folder for temporary .set storage
    mkdir TEMP

    % Run EEGLAB
    STUDY = []; CURRENTSTUDY = 0; ALLEEG=[]; EEG=[]; CURRENTSET=[]; 
    eeglab nogui % Better than to close the GUI afterwards

    % EEGlAB options
    % set double-precision parameter & allows to process more datasets while only keeping 1 in memory
    pop_editoptions('option_single', 0, 'option_storedisk',1); 

    % Epitome of UI
    h = waitbar(0,{'Loading' , ['Progress: ' '0 /' num2str(size(FileList,1))]});

    % Filling in the STUDY in EEGLAB
    for i=1:size(FileList,1)

        % Current file's path
        FilePath = [FileList(i).folder '\' FileList(i).name];

        % Waitbar updating
        waitbar(i/size(FileList,1),h,{strrep(FileList(i).name,'_','-'), ...
            ['Progress: ' num2str(i) '/' num2str(size(FileList,1))]})

        % Import the .bdf file 
        EEG = pop_biosig(FilePath,'channels',1:nbchan); 

        % Load channels location file
        EEG = pop_chanedit(EEG, 'load',{chanloc_path 'filetype' 'autodetect'});

        % Re-referencing, because chanedit erase the information
        EEG = pop_reref(EEG,ref_chan);
        
        % Adding information to the EEG file (relevant for BIDS)
        EEG.filename = FileList(i).name;
        EEG.filepath = FileList(i).folder;
        EEG.subject = num2str(SubjList(i));
        % 1.TASK INFORMATION
        if TaskPattern==1; EEG.task = Task{cellfun(@(x) contains(EEG.filename,x),Task)};
        elseif TaskPattern==2; EEG.task = Task{cellfun(@(x) contains(EEG.filepath,x),Task)};
        else; EEG.task = '';
        end
        
        % 2.RUN INFORMATION
        StrPattern = ['(?<=' strrep(Run,'*','') ')[0-9]*'];
        if RunPattern==1 % Matching pattern in files
            EEG.run = str2double(regexp(EEG.filename, StrPattern, 'match'));
        elseif RunPattern==2 % Matching patter in folders
            EEG.run = str2double(regexp(EEG.filepath, StrPattern, 'match'));
        else; EEG.run = [];
        end
        
        % 3.SESSION INFORMATION
        StrPattern = ['(?<=' strrep(Session,'*','') ')[0-9]*'];
        if SessionPattern==1 % Matching pattern in files
            EEG.session = str2double(regexp(EEG.filename, StrPattern, 'match'));
        elseif SessionPattern==2 % Matching patter in folders
            EEG.session = str2double(regexp(EEG.filepath, StrPattern, 'match'));
        else; EEG.session = [];
        end
        
        %%%% STEP 1: Edit BIDS Task Information %%%%
        % ----------------------------------- %
        % Filling up the EEG data structures with default settings (LNS lab)
        % EEG manufacturer information
        EEG.BIDS.tInfo.CapManufacturer = 'Electro-Cap International';
        EEG.BIDS.tInfo.CapManufacturersModelName = 'medium-small, medium, medium-large, large';
        EEG.BIDS.tInfo.EEGReference = 'Occipital between PO3 and POz';
        EEG.BIDS.tInfo.EEGGround = 'Occipital between POz and PO4';
        EEG.BIDS.tInfo.EEGPlacementScheme = '10-20';
        EEG.BIDS.tInfo.Manufacturer = 'BioSemi';
        EEG.BIDS.tInfo.ManufacturersModelName = 'ActiveTwo';
        EEG.BIDS.tInfo.DeviceSerialNumber = 'ADC16-11-758';
        EEG.BIDS.tInfo.SoftwareVersions = 'ActiView707';
        EEG.BIDS.tInfo.HardwareFilters = '3.6 Khz';
        EEG.BIDS.tInfo.SoftwareFilters = 'Hamming windowed sinc FIR filter [pop_eegfiltnew.m]';
        EEG.BIDS.tInfo.PowerLineFrequency = 50;
        
        % Institution information
        EEG.BIDS.tInfo.InstitutionName = 'University of Fribourg';
        EEG.BIDS.tInfo.InstitutionalDepartmentName = 'Neurosciences and Movement Sciences';
        EEG.BIDS.tInfo.InstitutionAddress = 'Fribourg, Switzerland';

        % Participant information
        % EEG(1).BIDS.pInfoDesc contains description of each variable
        % EEG(1).BIDS.pInfo contains data as cells
        if str2double(MetaData)==1 
            Idx = ismember(cellfun(@(x) strrep(x,'.set',''),PartInfoData(:,1),'UniformOutput',0),...
                strrep(EEG.filename,Extension,'')); % Find subject specific data 
            EEG.BIDS.pInfo(1,:) = PartInfoColNames; % First line is headers
            EEG.BIDS.pInfo(2,:) = PartInfoData(Idx,:); % Second line is data

            % contains description of each variable
            for m=1:size(PartInfoDesc,1)
                IdxPartInfoDesc = PartInfoDesc(m,cellfun(@(x) ~isempty(x), PartInfoDesc(m,:)));
                EEG.BIDS.pInfoDesc.(PartInfoDesc{m,1}).Description = PartInfoDesc{m,2};

                % Defining levels (if provided)
                if length(IdxPartInfoDesc)>2
                    Levels = unique(PartInfoData(:,m)); % find unique levels in data
                    Levels = Levels(cellfun(@(x) ~isempty(x),Levels)); % Removing empty fields
                    % replacing spaces (if any, not accepted for structure field names)
                    Levels = cellfun(@(x) strrep(x,' ','_'), Levels, 'UniformOutput', 0);
                    for n=3:length(IdxPartInfoDesc) % Fill in the structure
                        EEG.BIDS.pInfoDesc.(PartInfoDesc{m,1}).Levels.(Levels{n-2}) = IdxPartInfoDesc{n};
                    end
                end
            end
        end
        
        % Loading .mrk file and replacing the EEG.event and .urevent
        % structures (thanks to Hugo Najberg for the code lines)
        if ~isempty(mrk_folder)
            
            % opening the .mrk file and capturing its data (trigger type and latency)
            Idx = ismember(cellfun(@(x) strrep(x,'.mrk',''),{MRKList.name},'UniformOutput',0),...
                strrep(EEG.filename,Extension,'')); % Find subject specific data 
            
            if nnz(Idx)% The .mrk file may not exist
                filenameMRK = [MRKList(Idx).folder '\' MRKList(Idx).name];
                delimiter = '\t';
                startRow = 2;
                formatSpec = '%q%q%q%[^\n\r]';
                fileID = fopen(filenameMRK,'r');

                % Scanning the file
                dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');                       

                % deleting the structure EEG.event
                EEG = rmfield(EEG,{'event','urevent'});
                
                % Converting from ms to TF
                if Error_ms~=0; Error_TF = round(Error_ms/((1/EEG.srate)*1000));end

                % Creating the new EEG.event and EEG.urevent structures based on the .mrk data
                for row = 1:length(dataArray{1})
                    EEG.event(row).latency = str2num(cell2mat(dataArray{1}(row)))+Error_TF;
                    EEG.event(row).type    = str2num(cell2mat(dataArray{3}(row)));
                    EEG.urevent(row).latency = str2num(cell2mat(dataArray{1}(row)))+Error_TF;
                    EEG.urevent(row).type    = str2num(cell2mat(dataArray{3}(row)));
                    EEG.event(row).urevent = row;
                end
            end
        end

        % Save file as .set in temporary folder (will be emptied at the end)
        FileNameSet = strrep(EEG.filename,Extension,'.set');
        pop_saveset(EEG,[pwd '\TEMP\' FileNameSet]);  

        % Reload dataset (.set) from temp. folder
        EEG = pop_loadset(FileNameSet,[pwd '\TEMP\']);
        [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, i);

        % Filling the STUDY structure
        [STUDY,ALLEEG] = std_editset(STUDY, ALLEEG,'name', StudyName, 'commands',...
        {{'index' i 'load' [pwd '\TEMP\' FileNameSet] 'subject' num2str(SubjList(i))}},'updatedat','off'); 
    end

    % Waitbar end
    waitbar(1,h,{'Done !' , ['Progress: ' num2str(i) ' /' num2str(size(FileList,1))]});

    % Save STUDY
    [STUDY EEG] = pop_savestudy(STUDY, EEG, 'filename',[StudyName '.study'],...
    'filepath',pwd);

    % Reloading the STUDY
    [STUDY EEG] = pop_loadstudy('filename', [StudyName '.study'], 'filepath',pwd);
else
    % Select .study file to load
    [STUDY_file,STUDY_path] = uigetfile('.study', 'Select the STUDY file you would like to load');
    
    % Load provided .study file
    [STUDY EEG] = pop_loadstudy('filename',STUDY_file,'filepath',STUDY_path);
end

%% BUILD BIDS INFORMATION
% see : https://github.com/sccn/bids-matlab-tools/wiki

% Run the GUI
% Data are contained in each dataset's EEG.BIDS.tInfo and EEG.BIDS.gInfo
EEG = pop_taskinfo(EEG);

%%% STEP 2: Participant Info %%%%
% ----------------------------------- %
if str2double(MetaData)==2 
    EEG = pop_participantinfo(EEG, STUDY);
end

%%%% STEP 3: Event Info %%%%
% ----------------------------------- %
EEG = pop_eventinfo(EEG); 

%%%% STEP 4: Export BIDS structure %%%%
% ----------------------------------- %
pop_exportbids(STUDY, EEG,'targetdir',[pwd '\BIDS_EXPORT'])

%%%% STEP 5: Validate BIDS dataset %%%%
% Adopting Openneuro's command-line bids-validator
% https://github.com/bids-standard/bids-validator
pop_validatebids([pwd '\BIDS_EXPORT'])
% The ouputs looks terribly weird, I opened an issue (09.04.2021):
% https://github.com/bids-standard/bids-validator/issues/1262

% prompt output
fprintf('The script ran successfully and the output can be found in %s.',[pwd '\BIDS_EXPORT'])

%% REMOVE TEMPORARY DATA
% IF DO SO, WILL NOT BE ABLE TO RELOAD THE STUDY !!! 
% Removing TEMP folder with content (all .set files generated while creating
% the STUDY) ! 
% rmdir([pwd '\TEMP\'],'s');
